name: XTroll
main: me.TheJokerDev.XTroll.Main
version: 1.0-SNAPSHOT
api-version: '1.13'
author: TheJokerDev
commands:
  troll:
    usage: /troll
    description: Base command.
    aliases: [tr, xtroll, xtr]